import os
import pandas as pd
import yaml

OUTDIR='workflow/results'

RESEARCH_DATA = f'{OUTDIR}/research_data'
RESEARCH_METADATA = f'{OUTDIR}/research_metadata'
TEXT_DATA = f'{OUTDIR}/text_data'
INDEX_DATA = f'{OUTDIR}/index_data'
DONE = f'{OUTDIR}/done'

rule parse_text:
    input: RESEARCH_DATA
    output: TEXT_DATA
    shell:
        """
        python -m workflow.scripts.run_spacy --input {input} --output {output}
        """

rule process_text:
    input: TEXT_DATA
    output: INDEX_DATA
    shell:
        """
        python -m workflow.scripts.aaa --input {input} --output {output}
        python -m workflow.scripts.tf-idf 
        """

rule index_data:
    input: INDEX_DATA
    output: DONE
    shell:
        """
        docker-compose up -d --no-recreate
        sleep 30
        python -m workflow.scripts.index_data --input {input} --output {output}
        """


rule clean_for_build:
    shell:
        """
        echo 'Deleting files'
        rm -f {RESEARCH_DATA} {RESEARCH_METADATA} {TEXT_DATA} {INDEX_DATA}
        rm -f {OUTDIR}/*-aaa.npy
        """